language: objective-c 
matrix:
    include:
        - osx_image: xcode9

branches:
    only: master

before_install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - carthage bootstrap --no-use-binaries --platform ios

script:
    - xcodebuild -scheme RxTableViewCell  -sdk iphonesimulator | xcpretty -c

notifications:
    email: false
