language: objective-c 
matrix:
    include:
        - osx_image: xcode8.3

branches:
    only: master

before_install:
    - brew update
    - brew install carthage
    - carthage bootstrap --no-use-binaries --platform ios

script:
    - xcodebuild -sdk iphonesimulator | xcpretty -c
